Update vfs.js
os-js/osjs-server pull request #56
Opened 2021-08-29 06:21 UTC by mahsashadi

The implementation of createOptions method changes to support decoding of options passed by GET request.

2021-08-31 14:33 UTC, andersevenrud requested changes
Btw, this is what I came up with:

```javascript
const assembleQueryData = (object) => {
  const assembled = {}
  const keys = Object.keys(object)

  for (let i = 0; i < keys.length; i++) {
    const key = keys[i]
    const dots = key.split('.')

    let last = assembled
    for (let j = 0; j < dots.length; j++) {
      const dot = dots[j]
      if (j >= dots.length - 1) {
        last[dot] = object[key]
      } else {
        last[dot] = last[dot] || {}
      }

      last = last[dot]
    }
  }

  return assembled
}
```

2021-08-31 14:33 UTC, andersevenrud commented on src/vfs.js
> +  Object.keys(reqFileds).map((item) => {
I don't like the use of `map` here. This should probably be a `forEach`.

2021-08-31 14:33 UTC, andersevenrud commented on src/vfs.js
> +  console.log(options)
This does not belong here.

2021-08-31 14:34 UTC, andersevenrud commented
Also, the parsing could just happen in the utility function: https://github.com/os-js/osjs-server/blob/d25005050fbbee75245ea2fc31b6d26c5b6266a3/src/utils/vfs.js#L177

No need to touch the actual VFS code :thinking:

2021-09-03 14:28 UTC, mahsashadi commented
> No need to touch the actual VFS code

Oh, yes, no need to change vfs!

so should I have a commit  in `src/utils/vfs.js` with below changes? 


```js
/*
 * Parses URL Body
 */
const parseGet = req => {
  const {query} = url.parse(req.url, true);
  const assembledQuery = assembleQueryData(query);
  return Promise.resolve({fields: assembledQuery, files: {}});
};

/*
 * Assembles a given object query
 */
const assembleQueryData = (object) => {
  const assembled = {}
  const keys = Object.keys(object)

  for (let i = 0; i < keys.length; i++) {
    const key = keys[i]
    const dots = key.split('.')

    let last = assembled
    for (let j = 0; j < dots.length; j++) {
      const dot = dots[j]
      if (j >= dots.length - 1) {
        last[dot] = object[key]
      } else {
        last[dot] = last[dot] || {}
      }

      last = last[dot]
    }
  }
  return assembled;
}

```

2021-09-03 15:28 UTC, andersevenrud commented
If you feel like my suggestion was a better example, then feel free to commit that.

We'll be adding tests here so we know that it works properly.

2021-09-03 17:44 UTC, andersevenrud requested changes
Some minor stuff still to do here, including fixing the linting errors. I'll write a test for this and add it here.

2021-09-03 17:44 UTC, andersevenrud commented on src/utils/vfs.js
> +const assembleQueryData = (object) => {
1. Place this function above `parseGet`.
2. Use `export const` here so that the function can be tested.

2021-09-03 17:48 UTC, andersevenrud commented on src/utils/vfs.js
> +const assembleQueryData = (object) => {
Correction. I forgot this was not ESM. Don't add export, but place it in `module.exports` :D

2021-09-03 17:52 UTC, andersevenrud requested changes
Here is a test that you can add to `__tests__/utils/vfs.js`. It can be placed in the bottom of the `describe` scope. Since I don't have write access to your fork, this is probably the easiest way to do this :)

```js
  test('assembleQueryData', () => {
    const result = utils.assembleQueryData({
      'a': 'b',
      'b.a': 'foo',
      'b.b.a': 'foo',
      'b.b.b': 'foo',
      'b.b.c': 'foo',
      'b.b.d': 'foo',
      'b.b.e': 'foo',
      'c': 'null',
      'd': 'true',
      'e': '1'
    });

    expect(result).toEqual({
      a: 'b',
      b: {
        a: 'foo',
        b: {
          a: 'foo',
          b: 'foo',
          c: 'foo',
          d: 'foo',
          e: 'foo'
        }
      },
      c: 'null',
      d: 'true',
      e: '1'
    });
  });
```

2021-09-04 19:55 UTC, andersevenrud requested changes
I realized that we had not taken arrays into account here.

`?f.0=1&f.1=1&f.2=3` turns into:

```
    "f": {
        "2": "3"
    }
```

This is obviously wrong :D So this needs to be fixed as well.

2021-09-05 07:08 UTC, mahsashadi commented
> So this needs to be fixed as well.

Maybe first we should encode differently in client-side :-?
For example `f : ['a', 'b', 'c']` encoded like   `?f=a&f=b&f=c`, to detect in server-side values with same key are array items

2021-09-05 13:04 UTC, andersevenrud commented
> In this way it will be decoded correctly. We don't have to touch unserialization.

I believe that it's the underialization that needs to change. The client already does this correctly by having a sequence as keys, ex `a.0`, `a.1` and so on.

2021-09-05 13:22 UTC, mahsashadi commented
In this way, how we can distinguish between index and key 🤔 
`a.0=1` Can be both `a:{0:1}` and `a:[1]`

2021-09-05 13:27 UTC, andersevenrud commented
We can pretty much assume that it's an array if all the suffixes for the current key are numbers. 

> a.0=1 Can be both a:{0:1} and a:[1]

I don't understand what you mean by this.

2021-09-05 17:54 UTC, mahsashadi commented
I think we can replace [this line](https://github.com/mahsashadi/osjs-server/blob/146efc9335b9c68603765698d15479374ca8afa6/src/utils/vfs.js#L191) with :
` last[dot] = last[dot] || (/^\d+$/.test(dots[j + 1]) ? [] : {})`

2021-09-05 18:10 UTC, andersevenrud commented
Not sure that is 100% reliable. An object can have numbers as keys as well,
and this does not seem to handle cases where it is for example mixed.

You can check this by updating the test with the suggested change. I would
recommend using a test-driven workflow: write the test with the outcome you
want, then change the implementation. That way there's no need for guessing
:)

On Sun, Sep 5, 2021, 19:54 mahsashadi ***@***.***> wrote:

> I think we can replace this line
> <https://github.com/mahsashadi/osjs-server/blob/146efc9335b9c68603765698d15479374ca8afa6/src/utils/vfs.js#L191>
> with :
> last[dot] = last[dot] || (/^\d+$/.test(dots[j + 1]) ? [] : {})
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/os-js/osjs-server/pull/56#issuecomment-913198216>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABHODBHYESO62I23YQGBU3UAOVEXANCNFSM5C74ZRNQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-05 20:25 UTC, andersevenrud commented
We're starting to get somewhere now :smile: 

Could you please rebase this branch to the latest master so that the tests runs properly ? I discovered a race condition in the Core that prevents the tests from completing without doing a timeout which makes it impossible to check this PR :nerd_face:

2021-09-05 20:30 UTC, andersevenrud commented
Just a quick instruction on how to rebase quickly:

```
git fetch origin master:master
git rebase master
git push --force
```

2021-09-05 20:47 UTC, andersevenrud requested changes
I ran the latest commit of this locally and checked the test, and it looks good to me :+1: 

So after you've done a rebase then the only thing that is left is to add the type casting!

https://github.com/os-js/osjs-client/pull/165#discussion_r702322019

Nice work :)

2021-09-06 09:07 UTC, mahsashadi commented
> So after you've done a rebase then the only thing that is left is to add the type casting!

I have done this. the `assembleQueryData` test is Ok, but not the `parseFields - GET` [test](https://github.com/mahsashadi/osjs-server/blob/d1335a2a96c5d0b4f68816c8e7cf2af87272439c/__tests__/utils/vfs.js#L202) ! 
Is there something else need to be changed :thinking:

2021-09-06 11:26 UTC, andersevenrud approved these changes
Looks OK to me :)

2021-11-07 10:26 UTC, mahsashadi commented
Hi again :)
To continue work on filemanager pagination, I have commited some changes:

- system adapter implements capabilities method (suggested[ here](https://github.com/os-js/osjs-client/pull/164#issuecomment-913868931))
- totalCount and totalSize is added to stat (for filemanager statusBar, as suggested [here](https://github.com/os-js/osjs-client/issues/166#issuecomment-929494562))

2022-06-26 22:51 UTC, ajmeese7 commented
Whenever I try to check the codeclimate report to see why the check is failing, I'm just getting the message "We do not currently have an analysis of these two commits" and whenever I click "Analyze" nothing seems to happen. Could you let me know if this PR needs some work that I could help out with?

2022-06-26 22:55 UTC, andersevenrud commented
> Whenever I try to check the codeclimate report to see why the check is failing

Probably because they have a retention policy on logs and this one is expired :/

2022-07-07 22:21 UTC, ajmeese7 commented
@andersevenrud could you give an example of what you mean? If @mahsashadi doesn't have time to look into it I would be happy to give it a shot. Also, any updates on https://github.com/os-js/osjs-client/pull/165, since that was mentioned in this PR as well?

2022-07-19 10:49 UTC, mahsashadi commented
> ?options=<JSON serialized data>

So in client-side, we need to change [this method](https://github.com/mahsashadi/osjs-client/blob/e577c0250986e384006f957e2ba4ffbc400bfdbd/src/utils/fetch.js#L42) as below:
`export const encodeQueryData = (data) => (JSON.stringify(data));`

 In server-side, we can change [this method](https://github.com/mahsashadi/osjs-server/blob/948873cb21469ed9856d656ce82295d177a5a4e8/src/utils/vfs.js#L188) as below:
`const assembleQueryData = (object) => (JSON.parse(Object.keys(object)[0]))`

But I think you mean something else in server-side, can you explain more? @andersevenrud

2022-07-20 11:02 UTC, mahsashadi commented
> I believe there's a way to just use `body-parser` as a middleware for the VFS so a query string with JSON is parsed automatically.

I did not get the whole thing yet:

- As I know, `body-parser` is used for `POST` requests, while here we are sending options as a query string in `GET` request. So how can It help?
- Doing the `json-serialized` in client-side as you said, then everything works well in server-side. Just left `parseGet` method [as it was](https://github.com/os-js/osjs-server/blob/e5bd5196b827233e1b8e4bfd48cb74a30a20026c/src/utils/vfs.js#L177), then [this method](https://github.com/os-js/osjs-server/blob/e5bd5196b827233e1b8e4bfd48cb74a30a20026c/src/vfs.js#L113) will create expected options for us.

2022-07-20 12:52 UTC, andersevenrud commented
> As I know, body-parser is used for POST requests

Sorry, yes that's correct. Not sure what I was thinking here :)

> Doing the json-serialized in client-side as you said, ...

I don't understand this.

2022-07-20 17:58 UTC, mahsashadi commented
> I don't understand this.

With the code example you wrote above for serialization, seems nothing need to be change in sever… options are correctly unserialized and passed to vfs.

2022-07-20 20:06 UTC, andersevenrud commented
> With the code example you wrote above for serialization, seems nothing need to be change in sever… options are correctly unserialized and passed to vfs.

Since I was an idiot with the `body-parser` stuff, we have to implement some kind of deserialize on the server. But it would be as simple as just doing the opposite of the code example I gave :)

2022-07-23 13:49 UTC, mahsashadi commented
we can do this for unserialization:

```js
const assembleQueryData = (data) => {
  let assembled = {};
  for (const key in data) {
    try{
      const currentVal = JSON.parse(data[key]);
      assembled[key] = currentVal;
    }catch(e) {
      assembled[key] = data[key];
    }
  }
  return assembled;
};
```

2022-07-23 13:54 UTC, mahsashadi commented
> Almost. It would be something like:

I think here we are loosing some types for non-objects values. For example `options: undefined`

2022-07-23 14:18 UTC, andersevenrud commented
> I think here we are loosing some types for non-objects values. For example options: undefined

That won't really matter :)

2022-07-23 14:20 UTC, andersevenrud commented
> Is this method OK for unserialization?

Using native methods is a little bit nicer :)

```js
const entries = Object
  .fromEntries(data)
  .map(([k, v]) => {
    try {
      return [k, JSON.parse(v)]
    } catch (e) {
      return [k, v]
    }
  })

return Object.fromEntries(entries)
```

2022-07-24 06:24 UTC, mahsashadi commented
Thanks @andersevenrud  
I have committed mentioned changes both server and client side.
https://github.com/mahsashadi/osjs-client/commit/12d5b6527d2a658c5308855eb7335e77fca5397f
https://github.com/mahsashadi/osjs-server/commit/23b3c5756e67eda6b6bfd8cf3967284db25bfe0a

Just since `undefined` values are not supported by `JSON.stringify()`, I add a replacer function [here](https://github.com/mahsashadi/osjs-client/blob/12d5b6527d2a658c5308855eb7335e77fca5397f/src/utils/fetch.js#L36)

2022-07-24 15:21 UTC, andersevenrud commented
As mentioned in https://github.com/os-js/osjs-client/pull/165#issuecomment-1193338529 I would like to have the PR split up.

The same goes for this one.

2022-07-26 22:41 UTC, andersevenrud commented
Thanks for the split :ok_hand: 

since this branch now has so many commits and merges, and in addition to this now a conflict it might just be easier to open a new PR.

A small tip: Look into git **rebase** instead of doing merges. This will save you a little bit of pain when working with PRs when the master branch is updated.

2022-07-27 08:31 UTC, mahsashadi commented
> it might just be easier to open a new PR.

Great. Thanks. Since _unserialization_ PR is done, I think I should create two new PRs (spliting the rest):

1. Add VFS capabilities method, suggested [here](https://github.com/os-js/osjs-client/pull/164#issuecomment-913868931). 
2. Add totalCount and totalSize to VFS stats, suggested [here](https://github.com/os-js/osjs-client/issues/166#issuecomment-929494562).

If you agree, I will create these two PRs.

2022-07-27 19:06 UTC, andersevenrud commented
Agreed @mahsashadi

2022-07-28 21:34 UTC, andersevenrud commented
I'm closing this since we've agreed on a way to move forward.

I've also opened an issue where we can concentrate the discussion. Things got a bit confusing with the client/server stuff :D

2022-07-28 21:34 UTC, closed without merging

2022-07-28 21:34 UTC, andersevenrud commented
I'm closing this since we've agreed on a way to move forward.

I've also opened an issue where we can concentrate the discussion. Things got a bit confusing with the client/server stuff :D

https://github.com/os-js/OS.js/issues/804